import { useRef, useState, useEffect, useCallback } from "react";
import { cn } from "../lib/utils";
import { Send, Loader2, AlertTriangle, Menu } from "lucide-react";

interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: Date;
  error?: boolean;
}

interface ChatPageProps {
  onMenuClick: () => void;
  isDarkMode: boolean;
}

const initialMessages: Message[] = [
  {
    id: "1",
    role: "assistant",
    content: "Hello! I'm your AI assistant. How can I help you today?",
    timestamp: new Date(),
  },
];

export default function ChatPage({ onMenuClick, isDarkMode }: ChatPageProps) {
  const [messages, setMessages] = useState<Message[]>(initialMessages);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const chatRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to bottom when new messages arrive
  const scrollToBottom = useCallback(() => {
    if (chatRef.current) {
      chatRef.current.scrollTop = chatRef.current.scrollHeight;
    }
  }, []);

  useEffect(() => {
    scrollToBottom();
  }, [messages, loading, scrollToBottom]);

  const generateMessageId = (): string => {
    return Date.now().toString() + Math.random().toString(36).substr(2, 9);
  };

  const handleSend = useCallback(async () => {
    if (!input.trim() || loading) return;

    const userMessage: Message = {
      id: generateMessageId(),
      role: "user",
      content: input.trim(),
      timestamp: new Date(),
    };

    setMessages(prev => [...prev, userMessage]);
    setInput("");
    setError(null);
    setLoading(true);

    try {
      // Simulate API call
      await new Promise((resolve, reject) => {
        setTimeout(() => {
          // Simulate error 10% of the time
          if (Math.random() < 0.1) {
            reject(new Error("Failed to get response. Please try again."));
          } else {
            resolve("ok");
          }
        }, 1000 + Math.random() * 1000); // Random delay between 1-2 seconds
      });

      const assistantMessage: Message = {
        id: generateMessageId(),
        role: "assistant",
        content: "This is a mock response from the AI assistant. In a real application, this would be generated by an AI model like GPT.",
        timestamp: new Date(),
      };

      setMessages(prev => [...prev, assistantMessage]);
    } catch (err: any) {
      const errorMessage: Message = {
        id: generateMessageId(),
        role: "assistant",
        content: err.message || "An error occurred. Please try again.",
        timestamp: new Date(),
        error: true,
      };

      setMessages(prev => [...prev, errorMessage]);
      setError(err.message || "An error occurred");
    } finally {
      setLoading(false);
    }
  }, [input, loading]);

  const handleKeyDown = useCallback((e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  }, [handleSend]);

  const formatTime = (date: Date): string => {
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  };

  return (
    <div className={cn(
      "flex flex-col h-full transition-colors duration-200",
      isDarkMode ? "bg-gray-900" : "bg-white"
    )}>
      {/* Header */}
      <header className={cn(
        "flex items-center justify-between p-4 border-b",
        isDarkMode ? "border-gray-700 bg-gray-800" : "border-gray-200 bg-white"
      )}>
        <button
          onClick={onMenuClick}
          className={cn(
            "p-2 rounded-lg transition-colors",
            isDarkMode ? "hover:bg-gray-700" : "hover:bg-gray-100"
          )}
        >
          <Menu className="w-5 h-5 text-gray-600" />
        </button>
        <h1 className={cn(
          "text-lg font-semibold",
          isDarkMode ? "text-white" : "text-gray-900"
        )}>
          Chat
        </h1>
        <div className="w-10" /> {/* Spacer for centering */}
      </header>

      {/* Chat Messages */}
      <div 
        ref={chatRef}
        className="flex-1 overflow-y-auto px-4 py-4 space-y-4"
      >
        {messages.map((message) => (
          <div
            key={message.id}
            className={cn(
              "flex gap-3",
              message.role === "user" ? "justify-end" : "justify-start"
            )}
          >
            {message.role === "assistant" && (
              <div className="flex-shrink-0 w-8 h-8 rounded-full bg-green-500 flex items-center justify-center">
                <span className="text-white text-sm font-bold">AI</span>
              </div>
            )}
            
            <div className="max-w-[80%] space-y-1">
              <div
                className={cn(
                  "rounded-2xl px-4 py-3 text-sm",
                  message.role === "user"
                    ? "bg-blue-500 text-white"
                    : message.error
                    ? "bg-red-50 text-red-700 border border-red-200"
                    : isDarkMode
                    ? "bg-gray-700 text-white"
                    : "bg-gray-100 text-gray-900"
                )}
              >
                {message.error && (
                  <div className="flex items-center gap-2 mb-2">
                    <AlertTriangle className="w-4 h-4" />
                    <span className="text-xs font-medium">Error</span>
                  </div>
                )}
                <div className="whitespace-pre-wrap">{message.content}</div>
              </div>
              <div className={cn(
                "text-xs px-2",
                message.role === "user" 
                  ? isDarkMode ? "text-gray-400" : "text-gray-500"
                  : isDarkMode ? "text-gray-500" : "text-gray-400"
              )}>
                {formatTime(message.timestamp)}
              </div>
            </div>

            {message.role === "user" && (
              <div className="flex-shrink-0 w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center">
                <span className="text-white text-sm font-bold">U</span>
              </div>
            )}
          </div>
        ))}

        {/* Loading Indicator */}
        {loading && (
          <div className="flex gap-3 justify-start">
            <div className="flex-shrink-0 w-8 h-8 rounded-full bg-green-500 flex items-center justify-center">
              <span className="text-white text-sm font-bold">AI</span>
            </div>
            <div className="max-w-[80%] space-y-1">
              <div className={cn(
                "rounded-2xl px-4 py-3 text-sm",
                isDarkMode ? "bg-gray-700 text-white" : "bg-gray-100 text-gray-900"
              )}>
                <div className="flex items-center gap-2">
                  <Loader2 className="w-4 h-4 animate-spin text-gray-500" />
                  <span className={isDarkMode ? "text-gray-300" : "text-gray-600"}>
                    AI is thinking...
                  </span>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Input Area */}
      <div className={cn(
        "border-t p-4 transition-colors duration-200",
        isDarkMode ? "border-gray-700 bg-gray-800" : "border-gray-200 bg-white"
      )}>
        <form
          onSubmit={(e) => {
            e.preventDefault();
            handleSend();
          }}
          className="flex gap-3"
        >
          <div className="flex-1 relative">
            <textarea
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Type your message..."
              className={cn(
                "w-full resize-none rounded-2xl border px-4 py-3 pr-12 text-sm focus:outline-none focus:ring-2 transition-colors",
                isDarkMode
                  ? "bg-gray-700 border-gray-600 text-white placeholder-gray-400 focus:ring-blue-500 focus:border-transparent"
                  : "border-gray-300 text-gray-900 placeholder-gray-500 focus:ring-blue-500 focus:border-transparent"
              )}
              rows={1}
              disabled={loading}
              style={{
                minHeight: '44px',
                maxHeight: '120px',
              }}
            />
          </div>
          <button
            type="submit"
            disabled={!input.trim() || loading}
            className={cn(
              "flex-shrink-0 w-10 h-10 rounded-full flex items-center justify-center transition-colors",
              input.trim() && !loading
                ? "bg-blue-500 hover:bg-blue-600 text-white"
                : isDarkMode
                ? "bg-gray-600 text-gray-400 cursor-not-allowed"
                : "bg-gray-200 text-gray-400 cursor-not-allowed"
            )}
          >
            {loading ? (
              <Loader2 className="w-5 h-5 animate-spin" />
            ) : (
              <Send className="w-5 h-5" />
            )}
          </button>
        </form>

        {/* Error Message */}
        {error && (
          <div className="mt-3 p-3 bg-red-50 border border-red-200 rounded-lg">
            <div className="flex items-center gap-2 text-red-700 text-sm">
              <AlertTriangle className="w-4 h-4" />
              {error}
            </div>
          </div>
        )}
      </div>
    </div>
  );
} 